### ISSUE TITLE
Enhancement Request: Login with Eve to get access to my Regions Alliance Markets

### ISSUE THREAD

**Issue by RaynorUE** [raph5/eve-market-browser#1]
Hey there,

So glad to have this back in the world!! Just putting on the list that it would be great to allow ESI Login so someone could pull the private markets they have access to.

I know that raises concerns about those local markets. However, with this being open source now, it might be a good feature for folks to have for local/private hosting.

**Comment by raph5** [comment]
Hi, thank you!

Due to the bad design of the ESI market api, it’s almost impossible to get private market data. See the really good reddit post : https://www.reddit.com/r/Eve/comments/8hujh2/market_data_and_esi_a_short_story/
Basically the api requires you to have the private structure id but dont provide any way to get this id.
However it would be a nice feature to have. I could allow the users to add their own structure id list manually.

I think I wont add any special self hosting support as it seems there is not much demand.

**Comment by RaynorUE** [comment]
Ahh that makes sense, thanks for getting back to me!
